version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: clubapp-container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: clubs_db
      MYSQL_USER: dev_team_user
      MYSQL_PASSWORD: devpw123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
      - ./db:/var/lib/mysql-files
    command: --secure-file-priv="" --local-infile=1

volumes:
  db_data: